name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Set up Signing Files
      run: |
        mkdir -p .secret
        echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > ./.secret/my-release-key.jks
        echo "storeFile=./.secret/my-release-key.jks" > ./.secret/signing.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> ./.secret/signing.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> ./.secret/signing.properties
        echo "keyPassword=${{ secrets.KEY_ALIAS_PASSWORD }}" >> ./.secret/signing.properties
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
        KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}

    - name: Run Lint
      run: ./gradlew lintDebug
    
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Build Debug APK
      run: ./gradlew assembleDebug